# NumPy

In [5]:
import numpy as np
import pandas as pd

Question 1: Create a 4X2 integer array and Prints its attributes
Note: element must be a type of unsigned int16. And print the following Attributes: –

The shape of an array.
Array dimensions.
The Length of each element of the array in bytes.

In [4]:
arr=np.random.randint(0,100,8).reshape(4,2)
arr

array([[25, 50],
       [82, 58],
       [55, 56],
       [53, 64]])

In [5]:
print(arr.shape)

(4, 2)


Question 2: Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

In [7]:
arr2=np.arange(100,200,10).reshape(5,2)
arr2

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

Question 3: Following is the provided numPy array. return array of items in the third column from all rows
import numpy
sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
Expected Output:

Printing Input Array
[[11 22 33]
 [44 55 66]
 [77 88 99]]

 Printing array of items in the third column from all rows
[22 55 88]

In [13]:
sampleArray=np.array([[11,22,33],[44,55,66],[77,88,99]])
sampleArray
sampleArray[:,1]

array([22, 55, 88])

Question 4: Following is the given numpy array return array of odd rows and even columns
import numpy

sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
Expected Output:

Printing Input Array
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

 Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]

In [23]:
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]]) 
sampleArray


array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36],
       [39, 42, 45, 48],
       [51, 54, 57, 60]])

In [24]:
sampleArray[::2,1::2]

array([[ 6, 12],
       [30, 36],
       [54, 60]])

Question 5: Add the following two NumPy arrays and Modify a result array by calculating the square root of each element
import numpy

arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])
Expected Output:

addition of two arrays is 

[[20 39 33]
 [25 25 28]]

Result array after calculating the square root of all elements

[[ 400 1521 1089]
 [ 625  625  784]]

In [21]:
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]]) 
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]]) 


In [26]:
k=arrayOne+arrayTwo
k

array([[20, 39, 33],
       [25, 25, 28]])

In [27]:
k**2

array([[ 400, 1521, 1089],
       [ 625,  625,  784]], dtype=int32)

Question 7; Sort following NumPy array
7.1- by the second row and
7.2-by the second column
import numpy
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
Expected Output:

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]

Sorting Original array by secoond row
[[73 43 34]
 [12 22 82]
 [66 94 53]]

Sorting Original array by secoond column
[[82 22 12]
 [34 43 73]
 [53 94 66]]

In [25]:
sampleArray2 = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
sampleArray2

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [26]:
a1=sampleArray2
a2=sampleArray2

In [27]:
a2[:,[0,2]]=sampleArray2[:,[2,0]]
a2

array([[73, 43, 34],
       [12, 22, 82],
       [66, 94, 53]])

In [28]:
a1[[1,0]]=sampleArray2[[0,1]]
a1

array([[12, 22, 82],
       [73, 43, 34],
       [66, 94, 53]])

# Pandas

In [8]:
db=pd.read_csv(r"C:\Users\kaust\OneDrive\Desktop\Automobile_data.csv")
db.head()

index      company   body-style  wheel-base  length engine-type  \
0      0  alfa-romero  convertible        88.6   168.8        dohc   
1      1  alfa-romero  convertible        88.6   168.8        dohc   
2      2  alfa-romero    hatchback        94.5   171.2        ohcv   
3      3         audi        sedan        99.8   176.6         ohc   
4      4         audi        sedan        99.4   176.6         ohc   

  num-of-cylinders  horsepower  average-mileage    price  
0             four         111               21  13495.0  
1             four         111               21  16500.0  
2              six         154               19  16500.0  
3             four         102               24  13950.0  
4             five         115               18  17450.0

Question 6: Find the most expensive car company name
Print most expensive car’s company name and price.

Expected Output:

Python Pandas printing most costly car name

In [9]:
maxPrice=db['price'].max()
maxPrice

45400.0

In [10]:
db[db['price']==maxPrice][['company']]

company
35  mercedes-benz

Question 7: Find each company’s Higesht price car

In [11]:
db.groupby('company')['price'].max()

company
alfa-romero      16500.0
audi             18920.0
bmw              41315.0
chevrolet         6575.0
dodge             6377.0
honda            12945.0
isuzu             6785.0
jaguar           36000.0
mazda            18344.0
mercedes-benz    45400.0
mitsubishi        8189.0
nissan           13499.0
porsche          37028.0
toyota           15750.0
volkswagen        9995.0
volvo            13415.0
Name: price, dtype: float64

Question 8: Concatenate two data frames using the following conditions
Create two data frames using the following two Dicts, Concatenate those two data frames and create a key for each data frame.

GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]}
japaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}


In [22]:
GermanCars = {'Company': ['Ford', 'Mercedes', 'BMV', 'Audi'], 'Price': [23845, 171995, 135925 , 71400]} 
JapaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi '], 'Price': [29995, 23600, 61500 , 58900]}
df1=pd.DataFrame(GermanCars)
df2=pd.DataFrame(JapaneseCars)

In [24]:
frames=[df1, df2]
df_1_2=pd.concat(frames, keys=['x','y'])
df_1_2

Company   Price
x 0         Ford   23845
  1     Mercedes  171995
  2          BMV  135925
  3         Audi   71400
y 0       Toyota   29995
  1        Honda   23600
  2       Nissan   61500
  3  Mitsubishi    58900

Question 9: Sort all cars by Price column

In [18]:
sort=db.sort_values('price')
sort['company'].head()

13     chevrolet
27         mazda
48        toyota
36    mitsubishi
28         mazda
Name: company, dtype: object

Question 10: Count total cars per company

In [17]:
db.company.value_counts()

toyota           7
bmw              6
mazda            5
nissan           5
mitsubishi       4
mercedes-benz    4
audi             4
volkswagen       4
chevrolet        3
honda            3
alfa-romero      3
isuzu            3
jaguar           3
porsche          3
dodge            2
volvo            2
Name: company, dtype: int64

In [15]:
db[['company','index']].groupby('company').count()


index
company             
alfa-romero        3
audi               4
bmw                6
chevrolet          3
dodge              2
honda              3
isuzu              3
jaguar             3
mazda              5
mercedes-benz      4
mitsubishi         4
nissan             5
porsche            3
toyota             7
volkswagen         4
volvo              2